let state={accounts:[],settings:{},tasks:[]},current="dashboard";
const $=s=>document.querySelector(s);
async function boot(){state=await window.hoai.getState();renderAll();window.hoai.onTasks(x=>{state.tasks=x;renderQueue();renderDashboard();});window.hoai.onAccounts(x=>{state.accounts=x;renderAccounts();});window.hoai.onLog(renderLogs);document.querySelectorAll("#nav button[data-page]").forEach(b=>b.onclick=()=>show(b.dataset.page));}
function show(p){current=p;document.querySelectorAll(".page").forEach(x=>x.classList.add("hidden"));$("#"+p).classList.remove("hidden");document.querySelectorAll("#nav button").forEach(x=>x.classList.toggle("active",x.dataset.page===p));$("#title").textContent={dashboard:"Tổng quan",image:"Flow Ảnh",video:"Flow Video",accounts:"Tài khoản Flow",logs:"Log Chi Tiết",settings:"Cài Đặt"}[p]||p;renderAll();}
function renderAll(){renderDashboard();renderImage();renderVideo();renderAccounts();renderSettings();renderLogs();}
function renderDashboard(){$("#dashboard").innerHTML=`<div class="grid"><div class="card"><div class="muted">Tổng task</div><div class="metric">${state.tasks.length}</div></div><div class="card"><div class="muted">Hoàn thành</div><div class="metric ok">${state.tasks.filter(x=>x.status==="COMPLETED").length}</div></div><div class="card"><div class="muted">Đang chạy</div><div class="metric">${state.tasks.filter(x=>x.status==="GENERATING").length}</div></div><div class="card"><div class="muted">Tài khoản</div><div class="metric">${state.accounts.length}</div></div></div><div class="card" style="margin-top:18px"><h3 class="section-title">Queue</h3>${queueHtml()}</div>`}
function composer(type){let isImg=type==="image";return `<div class="composer"><div class="toolbar"><select id="${type}Model" class="select"><option value="">Model mặc định Flow</option>${isImg?'<option>Nano Banana 2 Lite</option>':'<option>Veo 3.1 - Quality</option><option>Omni 1.1 Flash</option>'}</select><select id="${type}Ratio" class="select"><option>16:9</option><option>9:16</option><option>4:3</option><option>1:1</option><option>3:4</option></select><select id="${type}Qty" class="select">${[1,2,3,4].map(x=>`<option>${x}</option>`).join("")}</select><select id="${type}Workers" class="select">${[1,2,3,4,5,6].map(x=>`<option ${x==state.settings.workers?"selected":""}>${x}</option>`).join("")}</select></div><textarea id="${type}Prompt" placeholder="Nhập prompt..."></textarea>${isImg?`<div class="muted" style="margin-top:12px">Ảnh tham chiếu — tối đa 3 ảnh cho mỗi prompt</div><div class="refs"><div class="ref">＋ Ảnh 1</div><div class="ref">＋ Ảnh 2</div><div class="ref">＋ Ảnh 3</div></div>`:""}<div class="toolbar"><button class="btn" onclick="addCurrent('${type}')">＋ Thêm prompt</button><button class="btn" onclick="importQueue()">📁 Import TXT / CSV / Excel / JSON</button><button class="btn primary" onclick="startRun()">▶ Chạy queue</button></div></div>`}
function renderImage(){if(current!=="image")return;$("#image").innerHTML=composer("image")+`<div class="card"><h3 class="section-title">Queue Flow Ảnh</h3>${queueHtml()}</div>`}
function renderVideo(){if(current!=="video")return;$("#video").innerHTML=composer("video")+`<div class="card"><h3 class="section-title">Queue Flow Video</h3>${queueHtml()}</div>`}
function queueHtml(){if(!state.tasks.length)return '<div class="empty">Chưa có prompt trong queue</div>';return `<table class="table"><tr><th>#</th><th>Prompt</th><th>Account</th><th>Tiến độ</th><th>Trạng thái</th><th>Output</th></tr>${state.tasks.map((t,i)=>{let a=state.accounts.find(x=>x.id===t.accountId);return `<tr><td>${i+1}</td><td><span class="pill">${t.mode==="image"?"Ảnh":"Video"}</span> ${esc(t.prompt).slice(0,100)}</td><td>${a?.email||"—"}</td><td><div class="bar"><i style="width:${t.progress||0}%"></i></div><span class="muted">${t.progress||0}% · ${t.stage||""}</span></td><td class="status ${t.status==="COMPLETED"?"ok":t.status==="FAILED"?"bad":""}">${t.status}${t.error?`<br><span class="bad">${esc(t.error)}</span>`:""}</td><td>${t.output?`<button class="btn" onclick="openFolder('${esc(t.output)}')">📂</button>`:"—"}</td></tr>`}).join("")}</table>`}
function renderAccounts(){if(current!=="accounts")return;$("#accounts").innerHTML=`<div class="toolbar"><button class="btn primary" onclick="addAccount()">＋ Thêm tài khoản</button></div><div class="card"><table class="table"><tr><th>Tài khoản</th><th>Email</th><th>Credit</th><th>Port</th><th>Trạng thái</th><th></th></tr>${state.accounts.map(a=>`<tr><td>${esc(a.name)}</td><td>${esc(a.email||"Chưa đăng nhập")}</td><td>${a.credit==null?"—":a.credit}</td><td>${a.port||"—"}</td><td>${a.status}</td><td><button class="btn" onclick="openAcc('${a.id}')">Mở</button><button class="btn" onclick="refreshAcc('${a.id}')">↻</button></td></tr>`).join("")}</table></div>`}
function renderSettings(){if(current!=="settings")return;let s=state.settings;$("#settings").innerHTML=`<div class="card"><h3 class="section-title">Cài đặt</h3><div class="setting-row"><b>Flow URL</b><input id="sFlow" class="input" value="${esc(s.flowUrl||"https://flow.google.com/")}"></div><div class="setting-row"><b>Thư mục output</b><div><input id="sOut" class="input" value="${esc(s.outputDir||"")}"><button class="btn" onclick="chooseOut()">Chọn thư mục</button></div></div><div class="setting-row"><b>Workers mặc định</b><input id="sWorkers" type="number" min="1" max="30" class="input" value="${s.workers||3}"></div><div class="setting-row"><b>Ngưỡng credit</b><input id="sCredit" type="number" min="0" class="input" value="${s.creditThreshold??10}"></div><div class="setting-row"><b>Timeout (ms)</b><input id="sTimeout" type="number" class="input" value="${s.timeoutMs||900000}"></div><button class="btn primary" onclick="saveSettings()">💾 Lưu cài đặt</button></div>`}
function renderLogs(){if(current!=="logs")return;window.hoai.getLogs().then(x=>{$("#logs").innerHTML='<div class="log">'+x.map(v=>`[${v.time}] ${v.level.toUpperCase()} ${v.message} ${JSON.stringify(v).replace(v.message,"")}`).join("\\n")+"</div>"})}
function addCurrent(type){const p=$("#"+type+"Prompt").value.trim();if(!p)return;window.hoai.addPrompt(p,type,[]);$("#"+type+"Prompt").value=""}
function importQueue(){window.hoai.importQueue()}
async function addAccount(){await window.hoai.addAccount();state=await window.hoai.getState();renderAll()}
async function openAcc(id){await window.hoai.openAccount(id);state=await window.hoai.getState();renderAll()}
async function refreshAcc(id){await window.hoai.refreshAccount(id);state=await window.hoai.getState();renderAll()}
async function startRun(){await window.hoai.start()}
async function chooseOut(){const p=await window.hoai.chooseDir();if(p)$("#sOut").value=p}
async function saveSettings(){await window.hoai.saveSettings({flowUrl:$("#sFlow").value,outputDir:$("#sOut").value,workers:Number($("#sWorkers").value),creditThreshold:Number($("#sCredit").value),timeoutMs:Number($("#sTimeout").value)});state=await window.hoai.getState();renderSettings()}
function openFolder(p){window.hoai.openFolder(p)}
function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
boot();